### ISSUE TITLE
AUR Arch linux packages

### ISSUE THREAD

**Issue by matheusfillipe** [lwthiker/curl-impersonate#10]
This is very interesting project, congratulations to the devs!

I have created 2 AUR packages for it using the dockerfiles as reference, fetching the patches from this repo.
They will install the `curl-impersonate-chrome` and `curl-impersonate-firefox` commands. I haven't added the scripts to add the browser headers though since they didn't matter much to me.

Maybe you would be interested on adding this to your readme?

https://aur.archlinux.org/packages/curl-impersonate-chrome
https://aur.archlinux.org/packages/curl-impersonate-firefox

**Comment by lwthiker** [comment]
This looks great, I can definitely add it to the README later.

About the wrapper scripts - their importance also comes from settings the correct `--ciphers` flag. It's different across browsers and even across versions (see the Firefox 95 vs the Firefox 91 scripts) and without it the TLS signature of curl wouldn't be identical to the browser. So I think it might be worth including them as well.

**Comment by matheusfillipe** [comment]
Alright,  I included the scripts.
