### ISSUE TITLE
How can I use this library with PHP on Mac

### ISSUE THREAD

**Issue by Jiri-Mihal** [lwthiker/curl-impersonate#105]
Hi,

At first thank you for this great library👍

I want to force PHP to use `curl-impersonate` instead of the standard `curl` library. How should I configure my system to achieve that? I see that there is a [solution for Linux](https://github.com/lwthiker/curl-impersonate/issues/100), but is there also a solution for macOS?

```sh
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
➜  ~ php -v
PHP 8.1.10 (cli) (built: Aug 30 2022 19:22:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
➜  ~ otool -L /usr/bin/curl
/usr/bin/curl:
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
➜  ~ 
```

**Comment by lwthiker** [comment]
I managed to make this work on a Mac I have (macOS 12.4, M1), can you try the following steps and see if it works for you as well?
1. Rename `libcurl-impersonate-chrome.dylib` to `libcurl.4.dylib` and place in some directory, say `/usr/local/lib`
2. Run php with the `DYLD_LIBRARY_PATH` env var pointing to that directory, for example:
```bash
DYLD_LIBRARY_PATH=/usr/local/lib php script.php
```

You can check if it works by running the following script:
```php
<?php
print_r(curl_version());
?>
```
If libcurl-impersonate was loaded correctly then you should see:
```
[ssl_version] => BoringSSL
```

**Comment by Jiri-Mihal** [comment]
Thank you for your prompt help. It works.
