### ISSUE TITLE
Custom Client Hello values

### ISSUE THREAD

**Issue by Kaspek2480** [lwthiker/curl-impersonate#106]
Is it possible to set custom values of Client Hello packet? 
Like with usage of `curl_easy_impersonate` set values of for example `CURLOPT_SSL_CIPHER_LIST` or `CURLOPT_SSL_EC_CURVES`

**Comment by lwthiker** [comment]
Not sure I fully understand the question.
When you use `curl_easy_impersonate()` it will set these options for you, you don't need to set the manually.
If you'd like to change them, you can use `curl_easy_setopt()` after the call to `curl_easy_impersonate()` and it will override whatever values that were previously set.

**Comment by alexio777** [comment]
i think its mean "JA3 finterprint"

**Comment by lwthiker** [comment]
Not all the values in the client hello are configurable with `curl_easy_setopt()`. In the upstream curl you can set some of them (for example the cipher list and the curves), and this project extends it for multiple other parameters as well. You can see the list here: https://github.com/lwthiker/curl-impersonate#libcurl-impersonate. There are TLS extensions and parameters which are not configurable.

**Comment by Kaspek2480** [comment]
Great, thanks for help guys
