### ISSUE TITLE
PyCurl example?

### ISSUE THREAD

**Issue by MortonPNZ** [lwthiker/curl-impersonate#111]
Newbee question, but can somebody, please, write a basic example how to use curl-impersonate in PyCurl instead of Curl?

**Comment by ycq0125** [comment]
https://github.com/ycq0125/pycurl
```
cd pycurl
C_INCLUDE_PATH=/usr/include/libxml2:/MyLib
# ex:C_INCLUDE_PATH=/usr/include/libxml2:/curl_test/curl-impersonate/build/curl-7.84.0/include
export C_INCLUDE_PATH
python3 setup.py install --curl-config=/usr/local/bin/curl-impersonate-chrome-config 
python3 test.py
```

**Comment by MortonPNZ** [comment]
> > Newbee question, but can somebody, please, write a basic example how to use curl-impersonate in PyCurl instead of Curl?
> > https://github.com/ycq0125/pycurl
> 
> ```
> cd pycurl
> C_INCLUDE_PATH=/usr/include/libxml2:/MyLib
> # ex:C_INCLUDE_PATH=/usr/include/libxml2:/curl_test/curl-impersonate/build/curl-7.84.0/include
> export C_INCLUDE_PATH
> python3 setup.py install --curl-config=/usr/local/bin/curl-impersonate-chrome-config 
> python3 test.py
> ```

Realy big thanks.

**Comment by Shleif91** [comment]
Can you tell me how to run pycurl + curl-impersonate in docker?

**Comment by MortonPNZ** [comment]
Nope, dont use docker... next step maybe, but now dont have any ideas

**Comment by gallamine** [comment]
To clarify: is there a way to `pip install pycurl` and then have it use curl-impersonate, or do I need to build pycurl from scratch?
