### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found

### ISSUE THREAD

**Issue by MyGitHub5** [lwthiker/curl-impersonate#114]
./curl-impersonate-ff: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by ./curl-impersonate-ff)
./curl-impersonate-ff: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./curl-impersonate-ff)
./curl-impersonate-ff: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./curl-impersonate-ff)

curl chrome works !
The Error is with curl ff (Firefox)...

**Comment by lwthiker** [comment]
You probably get this error because your local libc version does not match the one with which curl-impersonate was compiled. This can happen if you use an older Linux distribution (the binaries in this repository are compiled on Ubuntu 20.04). What Linux distribution and version are you running on?

**Comment by MyGitHub5** [comment]
Ubuntu Xenial (16.04 LTS)

**Comment by lwthiker** [comment]
Your glibc version is too old. I'd recommend to build curl-impersonate from source locally on your machine (or upgrade to a newer Ubuntu of course :) )
