### ISSUE TITLE
/usr/bin/env: 'ash': No such file or directory when using as docker Multi-stage 

### ISSUE THREAD

**Issue by foremtehan** [lwthiker/curl-impersonate#116]
1. Dockerfile : 

```
FROM php:8.1.1-cli-buster

COPY --from=lwthiker/curl-impersonate:0.5-chrome /usr/local/bin/ /usr/local/bin/
```
2. docker build -t test .

3. docker run -it test bash

4. curl_chrome101

the following error will ocurrs:

```
/usr/bin/env: 'ash': No such file or directory
```

What is wrong here ?

**Comment by lwthiker** [comment]
The Docker image `0.5-chrome` is based on Alpine Linux, and the wrapper scripts (`curl_chrome101` for example) use `ash` instead of `bash`. Please try and use the tag `0.5-chrome-slim-buster` instead

**Comment by foremtehan** [comment]
Now i got this error :

```
/usr/local/bin/curl-impersonate-chrome: error while loading shared libraries: libcurl-impersonate-chrome.so.4: cannot open shared object file: No such file or directory
```

**Comment by foremtehan** [comment]
Ok it's working now, thanks!

It would be nice if it working just like the first post (static i think?) and not like this:

```
COPY --from=lwthiker/curl-impersonate:0.5-chrome-slim-buster /usr/local/bin/ /usr/local/bin/
COPY --from=lwthiker/curl-impersonate:0.5-chrome-slim-buster /usr/local/lib/ /usr/local/lib/

RUN ldconfig
```

Because i use ffmpeg like this :

```
COPY --from=mwader/static-ffmpeg:4.4.1 /ffmpeg /usr/local/bin/
```

And it's working just fine. thanks btw.
