### ISSUE TITLE
configure error when trying to build current version on Ubuntu 20.04

### ISSUE THREAD

**Issue by A-Posthuman** [lwthiker/curl-impersonate#122]
Hi, I was able to build a prior version ok, but right now when trying to build the current version I get:

> cd curl-impersonate
> autoconf
> mkdir build && cd build
> ../configure
> 
> configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

Any ideas on what I might be missing? I'm building it on the same instance I previously built it ok, just deleted the git clone dir and re-cloned the current version.

**Comment by lwthiker** [comment]
Hi,

This has to do with some autoconf quirk on Ubuntu. It's also the reason the project now bundles the `configure` script. If you skip the `autoconf` step then it'll work.

**Comment by lwthiker** [comment]
I'm closing this, if the error persists please reopen.
