### ISSUE TITLE
HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by ypsik** [lwthiker/curl-impersonate#131]
Hello,

Many thanks for your effort, curl-impersonate worked very well, but stopped worked on akamai protected sites (like random site https://www.ea.com/) 5 days ago.
I'm getting error  HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) on Chrome profiles.
Same issue on original curl, just http 1.1 working well. Original Chrome working as well.
Maybe akamai founded a way to block curl http2 transfers now.  Would be nice if you can look inside if you have time.

**Comment by lwthiker** [comment]
Right now curl seems to be working well with this website (even upstream curl). Please open another issue if you have a more recent example of this problem.
