### ISSUE TITLE
Upgrade curl version to 7.86+ to support websocket

### ISSUE THREAD

**Issue by yifeikong** [lwthiker/curl-impersonate#157]
According to curl [docs](https://everything.curl.dev/libcurl/ws/support), it introduced websocket support in 7.86. Currently, curl-impersonate is based on 7.84, and latest curl version is 8.10. Could you please upgrade curl version to a more recent one?

> WebSocket is an EXPERIMENTAL feature present in libcurl 7.86.0 and later. Since it is experimental, you need to explicitly enable it in the build for it to be present and available.

**Comment by lwthiker** [comment]
Attempting to upgrade to curl 8.1.1 (latest): #160

**Comment by AndriusCTR** [comment]
> Attempting to upgrade to curl 8.1.1 (latest): #160

Any news? 

Thanks!

**Comment by lwthiker** [comment]
Updated to curl 8.1.1 in #160 and enabled websockets in #186 . However, the fingerprint does not yet completely match a browser's websocket fingerprint. This is tracked in a separate PR (#187).
