### ISSUE TITLE
[README] update installation instructions for macOS (missing dependencies)

### ISSUE THREAD

**Issue by ed9w2in6** [lwthiker/curl-impersonate#162]
I believe this is an _macOS_ issue only.

In short, 

The following dependencies are also needed in addition to the current listed dependencies:
- `libidn2`
- `librtmp`

On _macOS_ do: `brew install libidn2 rtmpdump`

Reason:
Both library are both _GNU_ hence some linux distribution may ship with both of them.  For instance on my Centos machine your instructions worked, in which _macOS_ does NOT.

**Comment by j0sh** [comment]
Getting the same here on an Intel macOS machine and the 0.5.4 release. In my case, zstd was also missing.

Shouldn't these libraries be statically complied into the build? Librtmp is also unnecessary and should be omitted from the build config.

For anyone else using Nixpkgs on Mac: I got this working under a Nix shell with `nix-shell -p libidn2 rtmpdump zstd` and adding the library paths (discovered via `pkg-config --libs`) to a `DYLD_FALLBACK_LIBRARY_PATH` environment variable to the `curl_chrome110` script. Something like this - the exact paths will vary:

```
DYLD_FALLBACK_LIBRARY_PATH=/nix/store/c4nas454dlkzgam9ihz0sdxqdjyjj3fi-libidn2-2.3.4/lib:/nix/store/shj1rqgqlh47xwg3mh007vbjkdvhnl49-rtmpdump-unstable-2021-02-19/lib:/nix/store/ly3wj661lbrgh5gj07kfx0y8cyqygrl0-zstd-1.5.5/lib "$dir/curl-impersonate-chrome" 
```

**Comment by j0sh** [comment]
Heads up that this issue still exists for MacOS. For those of you using nix on macos, the nixpkgs workaround mentioned earlier still works.

**Comment by lwthiker** [comment]
Thanks, I have taken a look and I see the problem now. The MacOS runner in GitHub comes with librtmp and libidn2 installed, and the curl build system automatically detects that and links them in. I think I'll explicitly disable them so the pre-compiled release binaries do not have them linked in (this is the case in the Linux binaries anyways).
