### ISSUE TITLE
Arch Linux problem: nss

### ISSUE THREAD

**Issue by bintesztelo** [lwthiker/curl-impersonate#163]
There is no nss package:
$ pacman -S nss ca-certificates
error: target not found: nss
warning: ca-certificates-20230311-1 is up to date -- reinstalling

**Comment by bashonly** [comment]
there is though: https://archlinux.org/packages/core/x86_64/nss/

maybe run `pacman -Syyu` and then try again

**Comment by lwthiker** [comment]
Doesn't seem like an issue in curl-impersonate, so I'm closing it.
