### ISSUE TITLE
Question: impersonate linux version of browsers

### ISSUE THREAD

**Issue by coderb** [lwthiker/curl-impersonate#179]
Should changing the User-Agent and sec-ch-* header strings to appropriate values be enough to fully impersonate the Linux versions of firefox102/chrome110?

Thank you.

**Comment by lwthiker** [comment]
Whenever I tested linux browsers they had identical fingerprint to their Windows counterpart. So most likely yes. Keep in mind that some websites will block you though because the user-agent is much less common.

**Comment by coderb** [comment]
thanks
