### ISSUE TITLE
Using curl-impersonate binaries from docker image inside my own image

### ISSUE THREAD

**Issue by windbridges** [lwthiker/curl-impersonate#189]
Could you tell me if I can use the binaries from the https://hub.docker.com/r/lwthiker/curl-impersonate image inside my image? 

Right now I'm building curl-impersonate completely from source inside dockerfile, but it's very slow. I want to get rid of that.

Why can't I just use the official image? For the reason that I use other php extensions besides curl-impersonate, and have my own Dockerfile.

As far as I understand, I need to copy some files from this image into my own so I can use the library. Any instructions on which files to copy?

**Comment by lhpalacio** [comment]
Yes, you can utilize the binaries from the curl-impersonate Docker image in your own image without building it from source every time.

Here's an example using a multi-stage build:

```yml
FROM lwthiker/curl-impersonate:0.5.4-chrome-alpine AS curl-impersonate

# Your base image
FROM php-x

# Copy curl-impersonate binaries and wrapper scripts from the builder stage
COPY --from=curl-impersonate /usr/local /usr/local

# Rest of your Dockerfile...

```

**Comment by windbridges** [comment]
> Yes, you can utilize the binaries from the curl-impersonate Docker image in your own image without building it from source every time.
> 
> Here's an example using a multi-stage build:
> 
> ```yaml
> FROM lwthiker/curl-impersonate:0.5.4-chrome-alpine AS curl-impersonate
> 
> # Your base image
> FROM php-x
> 
> # Copy curl-impersonate binaries and wrapper scripts from the builder stage
> COPY --from=curl-impersonate /usr/local /usr/local
> 
> # Rest of your Dockerfile...
> ```


Could you please advise what the problem could be?
```
FROM lwthiker/curl-impersonate:0.5.4-chrome-alpine AS curl-impersonate

FROM php:8.2-cli AS base

# ....

COPY --from=curl-impersonate /usr/local /usr/local

```

```
------
 > [php base  8/11] COPY --from=curl-impersonate /usr/local /usr/local:
------
failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/avlxqohz55jf4i4vl6jikhtrm/merged/usr/local/include/curl
```

**Comment by solariane** [comment]
for @windbridges , you seem to have a spurious **:** at the end of the path
> ------
>  > [php base  8/11] COPY --from=curl-impersonate /usr/local /usr/local:
> ------
> failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/avlxqohz55jf4i4vl6jikhtrm/merged/usr/local/include/curl
> ```

**Comment by solariane** [comment]
Hum, anyone has an idea of why even if the build is OK 
> FROM lwthiker/curl-impersonate:0.5-chrome as impersonatechrome
> FROM php:cli
> … PHP specific stuff
>  COPY --from=impersonatechrome /usr/local /usr/local

the binary are actually not working, got the following error : 
> /usr/local/bin/curl_chrome99: line 10: /usr/local/bin/curl-impersonate-chrome: cannot execute: required file not found

**Comment by solariane** [comment]
@windbridges or anyone coming here 

I made it work by issuing a 
> RUN rm -fR  /usr/local/include/curl

before the **COPY** command

And found another issue 
> error while loading shared libraries: libcurl-impersonate-chrome.so.4

so modify the **DOCKERFILE** to add 
> RUN ldconfig

after the **COPY**

**Comment by lwthiker** [comment]
This seems to be resolved so I'm closing it.

**Comment by ToshY** [comment]
@windbridges @solariane 

Do you have an example setup with Symfony and a Dockerfile that works (using the `CurlHttpClient`)? Would very much appreciate to have some information to set it up properly.
