### ISSUE TITLE
Macbook M1 Building from source.

### ISSUE THREAD

**Issue by d3vilsn0w** [lwthiker/curl-impersonate#190]
curl-impersonate/build/boringssl/crypto/../include/openssl/arm_arch.h:96:5: error: "unsupported ARM architecture"
#   error "unsupported ARM architecture"

Anyway we can successfully build this from mac m1?

**Comment by d3vilsn0w** [comment]
I was able to run this on the server ubuntu without any problems with precompiled library and it worked just fine when executing PHP file, but however for local development. I was trying to use libcurl mac build but it somehow doesn't work when running it within apache2 env.

**Comment by lwthiker** [comment]
With #217 merged, curl-impersonate now builds fine on Mac (tested on Mac M2).

I don't know exactly what went wrong in your case; please share more details if this issue persists.
