### ISSUE TITLE
support for 118

### ISSUE THREAD

**Issue by yuhhere** [lwthiker/curl-impersonate#199]
Any ETA when 118 would be supported?

**Comment by yuhhere** [comment]
@lwthiker

**Comment by yuhhere** [comment]
Can we please get an eta? @lwthiker, chrome 118's fingerprint seems to have changed

**Comment by yuhhere** [comment]
@lwthiker

**Comment by yuhhere** [comment]
119 out

**Comment by lwthiker** [comment]
I can confirm that the TLS fingerprint is different due to the presence of Encrypted Client Hello (ECH). Suppurting ECH will be tracked in #193.
