### ISSUE TITLE
On Mac: Can't execute curl-impersonate --cannot execute binary file

### ISSUE THREAD

**Issue by icesmartjuan** [lwthiker/curl-impersonate#24]
Thanks for publishing this useful tool.

Is it possible or any insights to run on Mac OS? currently it always throws error: `./curl_ff95 https://www.ha.com/c/search-results.zx
./curl_ff95: line 10: ./curl-impersonate: cannot execute binary file`

**Comment by lwthiker** [comment]
Hi,

Currently the build targets Linux only. Mac OS should be in the roadmap but currently not supported.
In the meantime you can run it in the container, for example
```
docker run --rm curl-impersonate-ff /build/out/curl_ff95 https://www.wikipedia.org
```

**Comment by icesmartjuan** [comment]
got that, thank you @lwthiker .

**Comment by lwthiker** [comment]
Support for macOS was now added in the main branch.

**Comment by ADannadata** [comment]
I failed to build the chrome version because BoringSSL was faded by the installed OpenSSL in my system.
To fix it in **Makefile.in** in the section **$(CURL_VERSION)/.chrome** insert
```
CPPFLAGS="-I$(boringssl_install_dir)/include" \
LDFLAGS="-L$(boringssl_install_dir)/lib" \
```
before or instead
```
CFLAGS="-I$(boringssl_install_dir)"
```

**Comment by gotham8x** [comment]
> Support for macOS was now added in the main branch.
Hi,
Thanks for your great contribution.
Could you please add pre-built binaries for macOS (amd64 & arm64) as people get troubles with building from source.
Thanks in advance.
