### ISSUE TITLE
can i use libcurl-impersonate.so in windows?

### ISSUE THREAD

**Issue by yuzd** [lwthiker/curl-impersonate#30]
can i use libcurl-impersonate.so in windows?

**Comment by yuzd** [comment]
i want to warp it on other lang ,ex: csharp or java

**Comment by lwthiker** [comment]
Hi, I didn't compile it for Windows yet. The `.so` file is for Linux only.

**Comment by yuzd** [comment]
ok i will test it on linux.
how to check the struct of  native method
```c
CURLcode curl_easy_impersonate(struct Curl_easy *data, const char *target);
```

**Comment by lwthiker** [comment]
Sorry not sure I understood the last question.
