### ISSUE TITLE
Add mobile browsers

### ISSUE THREAD

**Issue by vladtreny** [lwthiker/curl-impersonate#31]
Hello,

Thank you for your incredible work. 

Is it possible to add mobile browsers?  And probably others, like linux,  chrome on mac. 

Thank you

**Comment by vladtreny** [comment]
Sometimes also need linux browsers with correct fp. 

Also, can add brave, opera and etc.

**Comment by lwthiker** [comment]
From my experience the difference between the same browser running on mobile/winows/linux is just in the user agent. At this point the number of signatures becomes pretty much infinite - every phone model, android version, linux version has a different user agent. I could add one mobile phone signature as an example.

If you'd like a specific mobile browser/android version/phone model:
* Copy the wrapper script, for example `chrome/curl_chrome99`
* Change the line `-H 'User-Agent: ...'` and put the relevant user agent, for example from here https://developers.whatismybrowser.com/

Out of interest - Is there any specific use case for mobile browsers that doesn't work with the desktop ones?

**Comment by vladtreny** [comment]
hello,
yes, there is a tiny difference that can be used to validate the os

**Comment by lwthiker** [comment]
https://github.com/lwthiker/curl-impersonate/pull/35 adds support for Chrome on Android.

**Comment by vladtreny** [comment]
> From my experience the difference between the same browser running on mobile/winows/linux is just in the user agent. At this point the number of signatures becomes pretty much infinite - every phone model, android version, linux version has a different user agent. I could add one mobile phone signature as an example.
> 
> If you'd like a specific mobile browser/android version/phone model:
> 
> * Copy the wrapper script, for example `chrome/curl_chrome99`
> * Change the line `-H 'User-Agent: ...'` and put the relevant user agent, for example from here https://developers.whatismybrowser.com/
> 
> Out of interest - Is there any specific use case for mobile browsers that doesn't work with the desktop ones?

Opps, sorry did not read properly your last questions. 

Well, there is a community where we solve every possibility to detect bots. Mostly, work with cdp (without wrappers like puppeteer, because they create more problems than solve). During the last year, I think we won on client-side, solved everything.

But nearly 90% of sites, even 99, do not have such sophisticated protection, so cdp is overkill, they do not check fingerprints on client-side + many vendors do not block mobile at that rate,  because it is harder to spoof mobile browsers (however, I will be moving to mobile bots) + easier to blend in with the crowd.
