### ISSUE TITLE
How to compile this project on Windows?

### ISSUE THREAD

**Issue by NabiKAZ** [lwthiker/curl-impersonate#36]
How to compile this project on Windows?
If possible, put a guide or trick to compile the project on Windows? Without using Docker.

**Comment by lwthiker** [comment]
I didn't experiment with compiling it natively on Windows. You can, however, use WSL (Windows Subsystem for Linux) with Ubuntu:

Compile `curl-impersonate` using the Dockerfile
```
docker build -t curl-impersonate-chrome chrome/
```
then copy `/build/out/curl-impersonate` and `/build/out/curl_chrome99` from the docker image (i.e. by creating a temporary container and using `docker cp`).

The binary works well on WSL (tested with Windows 10 and the Ubuntu app)

**Comment by lwthiker** [comment]
I've opened this https://github.com/lwthiker/curl-impersonate/issues/37 to note the requirement of a native Windows build. So I'm closing this issue for now.
