### ISSUE TITLE
TCP fingerprinting

### ISSUE THREAD

**Issue by qmix2** [lwthiker/curl-impersonate#38]
It seems like fingerprinting is also possible based on TCP/IP parameters: https://incolumitas.com/2021/03/13/tcp-ip-fingerprinting-for-vpn-and-proxy-detection/.

I don't know if this fingerprinting method has widespread use, or how feasible it is to change the TCP settings on a per-socket basis, but maybe it's worth looking into it?

**Comment by lwthiker** [comment]
Thanks, this is interesting. The method could possibly be used to identify that a Linux machine is running `curl-impersonate` as a Windows browser. I haven't seen this in use anywhere currently but worth keeping an eye out.

**Comment by momala454** [comment]
I think that when using proxies, the tcp fingerprint will be the one from the proxy. So having a linux tcp fingerprint on a windows user agent is not a strong signal

**Comment by lwthiker** [comment]
I'm closing this as there currently isn't a plan to add TCP impersonation. It is not a strong indicator of a browser and doesn't seem to be used anywhere for web fingerprinting.
