### ISSUE TITLE
Dockers hangs on multiple requests

### ISSUE THREAD

**Issue by barrosa1987** [lwthiker/curl-impersonate#40]
Awesome project, congrats!

The only problem that I found its that the docker hangs when you try to do simultaneous requests.

Do you know how can fix this?

I am trying to execute 100 times curl_chrome99 at the same time.

**Comment by lwthiker** [comment]
Hi,

Can you please share the way you are running it?

**Comment by lwthiker** [comment]
@barrosa1987 Please try with the native build instead of Docker (see [INSTALL.md](https://github.com/lwthiker/curl-impersonate/blob/main/INSTALL.md)) and re-open this issue if the problem persists.
