### ISSUE TITLE
libcurl-impersonate-ff.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by iqbalhusen** [lwthiker/curl-impersonate#46]
After building and installing the package, when i try to run the command, it raises error

/usr/local/bin/curl-impersonate-ff: error while loading shared libraries: libcurl-impersonate-ff.so.4: cannot open shared object file: No such file or directory

**Comment by lwthiker** [comment]
You are right, it seems like Ubuntu is not looking for libraries in `/usr/local/lib` where the library is installed by default. For some reason in the automatic tests it does work. I'll look into the correct way of fixing this, in the meantime please try adding `/usr/local/lib` to your library path (see here for example https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib), or run with `LD_LIBRARY_PATH=/usr/local/lib curl_ff98 ...`

**Comment by lwthiker** [comment]
Another option is to compile statically with `./configure --enable-static`

**Comment by lamoquette** [comment]
Thanks for your reactivity ! I got the same error few minutes ago

**Comment by lwthiker** [comment]
Please try and run `sudo ldconfig` after doing `make install`, it should refresh the linker's cache which should then be able to find libcurl-impersonate in `/usr/local`. The INSTALL.md file was updated accordingly. If the issue persists please re-open.
