### ISSUE TITLE
`curl_easy_impersonate()` adds Accept-Encoding to req. headers w/out enabling cURL's auto decompression

### ISSUE THREAD

**Issue by qwerty12** [lwthiker/curl-impersonate#48]
Hi,

Not sure if this is actually a feature, but calling `curl_easy_impersonate(self.session, "ff98")` adds `Accept-Encoding: gzip, deflate, br` to the request headers, as expected, Most sites will respond by sending back compressed content, but libcurl won't perform its automatic decompression on the contents. 

While it's no problem to set `CURLOPT_ACCEPT_ENCODING`, before/after calling `curl_easy_impersonate`, to enable automatic decompression on received contents, it requires the coder to know what `Accept-Encoding` value `curl_easy_impersonate` sets.

**Comment by lwthiker** [comment]
Thanks, I've added a call to set `CURLOPT_ACCEPT_ENCODING` to an empty string which enables all built-in compressions. According to my testing this solves the problem.

**Comment by qwerty12** [comment]
Thank you. I applied your fix manually, took out the line that sets `CURLOPT_ACCEPT_ENCODING` in my code and can confirm that reading a compressed page from the same site worked.
