### ISSUE TITLE
New browser signatures (Firefox 99, Chrome 100, Safari 15.4)

### ISSUE THREAD

**Issue by lwthiker** [lwthiker/curl-impersonate#52]
New browsers are out and it will be good to have their signatures supported.

- Firefox 99
- Chrome 100
- Edge 100 ?
- Safari 15.4

**Comment by GunGunGun** [comment]
Please add Pale Moon, it's a good niche browser.

**Comment by lwthiker** [comment]
Support for Chrome/Edge 100,101 is in https://github.com/lwthiker/curl-impersonate/pull/64

**Comment by lwthiker** [comment]
Safari 15.5 was added in #84
