### ISSUE TITLE
support build on Amazon Linux(or centos, redhat linux)

### ISSUE THREAD

**Issue by DiveInto** [lwthiker/curl-impersonate#58]
thought this should be quite similar to build on Ubuntu, tried for hours but failed

my efforts include:
- install build prerequisites by: `sudo yum groupinstall "Development Tools"`
- upgrade cmake by: `pip3 install cmake --upgrade`
- create symbolic link for ninjia-build by: `ln -s /usr/bin/ninja-build /usr/bin/ninja`
- install nss by: `sudo yum install libnss3.so libnssutil3.so`
- add search path(`/usr/lib/`) for lib nss in [curl-impersonate.patch#](https://github.com/lwthiker/curl-impersonate/blob/0c6d1ab92baa5baa36aaefc6c6697fe1c98d7642/firefox/patches/curl-impersonate.patch#L1057):
  ```diff
  -+          search_paths="/usr/lib/$host /usr/lib/$host/nss"
  ++          search_paths="/usr/lib/ /usr/lib/$host /usr/lib/$host/nss"
  ``` 

still failed when doing `make firefox-build`, the log suggested failed linking NSS:
```
configure: WARNING: Using hard-wired libraries and compilation flags for NSS.
checking if libnssckbi is in a non-standard location... /usr/lib
checking for SSL_VersionRangeSet in -lnss_static... no
configure: error: Failed linking NSS statically
Makefile:198: recipe for target 'curl-7.81.0/.firefox' failed
make: *** [curl-7.81.0/.firefox] Error 1
```

the related log in `./curl-7.81.0/config.log` is:
```
...
configure:26797: checking if libnssckbi is in a non-standard location
configure:26815: result: /usr/lib
configure:26843: checking for SSL_VersionRangeSet in -lnss_static
configure:26865: gcc -o conftest -I/home/ec2-user/apps/curl-impersonate/buil
d/nss-3.75/dist/Release/../public/nss -I/home/ec2-user/apps/curl-impersonate
/build/nss-3.75/dist/Release/include/nspr -Werror-implicit-function-declarat
ion -O2 -Wno-system-headers    -I/home/ec2-user/apps/curl-impersonate/build/
brotli-1.0.9/out/installed/include -I/home/ec2-user/apps/curl-impersonate/bu
ild/nss-3.75/dist/Release/include -L/home/ec2-user/apps/curl-impersonate/bui
ld/nss-3.75/dist/Release/lib -Wl,-rpath,/usr/lib    -L/home/ec2-user/apps/cu
rl-impersonate/build/brotli-1.0.9/out/installed/lib conftest.c -lnss_static
 -Wl,--start-group -lssl -lnss_static -lpk11wrap_static -lcertdb -lcerthi -l
nsspki -lnssdev -lsoftokn_static -lfreebl_static -lnssutil -lnssb -lcryptohi
 -l:libplc4.a -l:libplds4.a -l:libnspr4.a -lsqlite -lgcm-aes-x86_c_lib -lhw-
acc-crypto-avx -lhw-acc-crypto-avx2 -lsha-x86_c_lib -lintel-gcm-wrap_c_lib -
lintel-gcm-s_lib -Wl,--end-group -pthread -ldl -lbrotlidec-static -lbrotlico
mmon-static -lz  >&5
/usr/bin/ld: cannot find -lbrotlidec-static
/usr/bin/ld: cannot find -lbrotlicommon-static
collect2: error: ld returned 1 exit status
configure:26865: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.se/mail/"
...
```

any help is appreciated

**Comment by lwthiker** [comment]
Seems like the actual issue is with linking with libbrotli, not NSS. Do you have `.a` files in `/home/ec2-user/apps/curl-impersonate/build/brotli-1.0.9/out/installed/lib`? The curl build looks for `libbrotlidec-static.a` and `libbrotlicommon-static.a`.

**Comment by DiveInto** [comment]
turns out brotli directory at amazon linux is at `build/brotli-1.0.9/out/installed/lib64`

have to update [the diff patch file](https://github.com/lwthiker/curl-impersonate/blob/0c6d1ab92baa5baa36aaefc6c6697fe1c98d7642/firefox/patches/curl-impersonate.patch#L21-L34) to:

```diff
diff --git a/configure.ac b/configure.ac
index 63e320236..68489985d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1331,10 +1331,11 @@ if test X"$OPT_BROTLI" != Xno; then

   dnl if given with a prefix, we set -L and -I based on that
   if test -n "$PREFIX_BROTLI"; then
-    LIB_BROTLI="-lbrotlidec"
-    LD_BROTLI=-L${PREFIX_BROTLI}/lib$libsuff
+    # curl-impersonate: Use static libbrotli
+    LIB_BROTLI="-lbrotlidec-static -lbrotlicommon-static"
+    LD_BROTLI=-L${PREFIX_BROTLI}/lib64$libsuff
     CPP_BROTLI=-I${PREFIX_BROTLI}/include
-    DIR_BROTLI=${PREFIX_BROTLI}/lib$libsuff
+    DIR_BROTLI=${PREFIX_BROTLI}/lib64$libsuff
   fi

   LDFLAGS="$LDFLAGS $LD_BROTLI"
```

this makes `make firefox-build` succeed, while `sudo make firefox-install` failed with:

```
$ sudo make firefox-install
cd curl-7.81.0
make install-exec MAKEFLAGS=
# Wrapper scripts for the Firefox version (e.g. 'curl_ff98')
cp -f /home/ec2-user/apps/curl-impersonate/build/../firefox/curl_ff* /usr/local/bin
bash: - : invalid option
make: *** [firefox-install] Error 1
```

have no idea what the error is, but running the install steps directly in the `build/curl-7.81.0` directory works, so finally I get my `curl_ff98` at `/usr/local/bin/`

**Comment by DiveInto** [comment]
and feel free to close this issue if you have no plan to support Amazon Linux in the near future.

thanks for your work again ❤️

**Comment by lwthiker** [comment]
Supporting Amazon Linux/RedHat is definitely something I would like. However this seems like it might be an issue with the upstream curl when using `--with-brotli` flag to the configure script. Anyway it's worth checking out further.

**Comment by jlarmstrongiv** [comment]
Support for AWS Linux would be great!  Currently, there’s two common [versions](https://hub.docker.com/_/amazonlinux):
- Amazon Linux 2 (based on CentOS 7)
- Amazon Linux 2022 (based on Fedora 34/35)

You can run them locally:
```bash
docker run --entrypoint /bin/bash -it -v "$PWD":/var/task amazonlinux:2022
```
