### ISSUE TITLE
How to cleanly uninstall curl-impersonate?

### ISSUE THREAD

**Issue by KirianCaumes** [lwthiker/curl-impersonate#59]
Hi,

I'm not gonna lie, I don't know much about how this project works, and some of it's concept are way beyond me, but I wanted to give it an eye for scraping something.

The thing is, now I want to uninstall this project.

So I deleted the folder where I cloned the repo and remove some stuff installed with apt, but I still have acces to the command `curl_chrome99`.

Is there a procedure to how to cleanly uninstall curl-impersonate?

Thanks by advance 😀

**Comment by lwthiker** [comment]
Hi,

`make firefox-uninstall` or `make chrome-uninstall` will do the trick. Make sure to run `configure` the same way as before.

Alternatively remove everything manually
```bash
rm -f /usr/bin/curl-impersonate-*
rm -f /usr/bin/curl_*
rm -f /usr/lib/libcurl-impersonate-*
```
(`ls` these files before to make sure you are not removing something else)

**Comment by KirianCaumes** [comment]
Hey, thanks for your answer!

I've executed the 3 `rm -f`, so those folders no longer exist.

But I still have access to to the command `curl_chrome99 https://www.wikipedia.org`, and it works.

Is there a way to delete the command?

**Comment by lwthiker** [comment]
Sorry I had a mistake in my comment. I edited it, please try again.

**Comment by KirianCaumes** [comment]
That's perfect, thanks a lot!
