### ISSUE TITLE
add available browsers as json file

### ISSUE THREAD

**Issue by vladtreny** [lwthiker/curl-impersonate#74]
Hello, is it possible to create a json file where list all available browsers and current docker image

like

```
{
'docker': 'lwthiker/curl-impersonate:0.4',
'browsers': {
    'chrome98': 'chrome',
    'chrome99': 'chrome',
    'edge98': 'chrome',
    'edge99': 'chrome',

    'safari15_3': 'chrome',

    'ff91esr': 'ff',
    'ff95': 'ff',
    'ff98': 'ff'
}
}

```

Of course can add more details to each browser

**Comment by lwthiker** [comment]
Hi,

As for the docker image - I'm not sure whether maintaining the last docker version in a file in the repo is the best idea. These things tends to go out of sync. If you are looking for a method to obtain the latest image, you can check the latest git tag, and the version of the docker image should match the version in git. Or, you can pull the `latest` tag (which currently points to the Firefox version by default).

As for the list of browsers - yes it makes sense indeed to maintain such a list as part of the project. Can I ask what would be your use of such a list?

**Comment by vladtreny** [comment]
For automation.  Now need to check manually the new versions of docker and browsers.   But could just load this json from your repo and auto-update software on fly.  I use random browsers, just shuffle the list

**Comment by vladtreny** [comment]
great.  it is possible to add these also a current docker version?   like.  docker_version: 0.5
