### ISSUE TITLE
Distribute binaries, including a drop-in replacement for the shared library

### ISSUE THREAD

**Issue by somini** [lwthiker/curl-impersonate#8]
Thanks for publishing this.

I see the release process is fairly automated, is it possible to use CI to automatically build binaries of this, and publish them as releases?
I don't have experience in Github Actions, but I do in Gitlab CI.
Both containers take 3 GB, but the binaries themselves are only ~7 MB.

Another interesting build artefact would be to "bake in" the settings in [curl_ff95](https://github.com/lwthiker/curl-impersonate/blob/main/firefox/curl_ff95) script in the build itself, and create a regular curl shared library. This could replace with the upstream libcurl file to use the new settings, or hacked around with `LD_LIBRARY_PATH`.
It would need to be a different build per browser.

Now curl is built in static mode. The library itself is in `lib/.libs/libcurl.a`.

**Comment by lwthiker** [comment]
Thanks for the suggestions.

I agree about `libcurl`, I believe many would find it useful. If we "bake in" all the settings directly it would result in many copies of `libcurl`, one for each browser version. If we support 10 Chrome versions then we'll have 10 different libcurls. Maybe a better solution would be to add a function to libcurl that configures everything the right way? But then `LD_LIBRARY_PATH` wouldn't work as you suggested.

I used GitHub Actions for small projects only; I don't know if it supports our heavy builds for free. Worth a try I guess. Would be good to have it to automatically check PRs, together with the new testing infra (https://github.com/lwthiker/curl-impersonate/pull/9).

About publishing, I'm not sure whether the binaries would be useful by themselves, as they are compiled for a specific Ubuntu/Debian and have external dependencies. Maybe publishing a .deb/.rpm package? I'm really not a packaging expert though.

**Comment by somini** [comment]
> Maybe a better solution would be to add a function to libcurl that configures everything the right way?

Of course, this is the end game. This is really a stop-gap solution. My usecase is really other applications that link directly to libcurl. Even if libcurl includes these changes, it might not be immediate to update.

> About publishing, I'm not sure whether the binaries would be useful by themselves, as they are compiled for a specific Ubuntu/Debian and have external dependencies.

Each distro has it's own package, so the dependencies would be installed automatically. Compiling the curl binaries would still be useful, since most dependencies are statically compiled.
The missing dependencies can be solved by installing the distro curl.

**Comment by lwthiker** [comment]
I see, so one possibility is to set all the command line parameters and headers in one of libcurl's initialization functions. It could depend on some env var so that we don't need different libcurl compilations for different browser versions (the cipher list, the user agents, etc. are changing every version). Then it might be possible to just replace libcurl for an existing application using `LD_LIBRARY_PATH`. Worth a try.

**Comment by somini** [comment]
Sorry for disappearing, this notification got lost in a sea of other notifications, I only had time to get back to this now.
I'm still very much interested.

#13 sounds perfect, I'm still working on building this and test it with a proper application (RSS Bridge, in this case).
I'm trying to build the AUR package and hit a snag: https://aur.archlinux.org/packages/curl-impersonate-firefox#comment-859457

**Comment by somini** [comment]
Finally got to test this and it very much works as intended, thanks. The AUR packages can be built without errors.

Any progress on getting something like this upstreamed on cURL? I think NSS is being dropped from curl, so once that hits, impersonating firefox is out of the question.

**Comment by jlarmstrongiv** [comment]
As far as I’m aware, there’s no limit on Github Actions for [public](https://github.community/t/for-public-repositories-is-there-a-monthly-limit-on-minutes/129017) repos, so it’d be worthwhile to use the use the CI to automatically build binaries.

The only limiting factor with GitHub actions that I have found is Dockerhub pull [rate limiting](https://github.com/actions/virtual-environments/issues/1445#:~:text=DockerHub%20will%20use%20IP%20rate,rate%20limits%20in%20GitHub%20Actions.), but I never bothered to setup [sign-ins](https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/).

**Comment by jlarmstrongiv** [comment]
GitHub Actions can also build on different platforms, e.g. MacOS and Windows, which would help solve issues like https://github.com/lwthiker/curl-impersonate/issues/24

**Comment by lwthiker** [comment]
I'm working on a Makefile based build that will compile `curl-impersonate` natively, without the Docker containers. Once this is up and working it'll be possible to add GitHub Action to automatically compile and MacOS and Linux.

**Comment by lwthiker** [comment]
Binaries for Linux & macOS are now automatically built and distributed in the GitHub release page. You can find the latest binaries in release [v0.4.1](https://github.com/lwthiker/curl-impersonate/releases/tag/v0.4.1).

**Comment by lwthiker** [comment]
You are right only the static binary is currently being built automatically. Do you need a pre-built libcurl in addition?

**Comment by momala454** [comment]
personally I do for ease of updating

**Comment by lwthiker** [comment]
libcurl-impersonate binaries are also added right now to the release page.
