### ISSUE TITLE
User supplied HTTP headers are wrongly ordered when using libcurl-impersonate

### ISSUE THREAD

**Issue by lwthiker** [lwthiker/curl-impersonate#90]
When using libcurl-impersonate (either with `CURL_IMPERSONATE` env var or `curl_easy_impersonate()`, user-supplied HTTP headers will be placed after the built-in list of HTTP headers that libcurl-impersonate uses.

If the user supplies a HTTP header with the `CURLOPT_HTTPHEADER` option, it will either:
- Replace the built-in header used for impersonation, if it's the same header (e.g. User-Agent).
- Be placed after all the built-in headers used for impersonation.

The result is that the order of HTTP headers is not fully controllable by the user.

Example:
When impersonating Chrome 101, the following headers are added by default:
```
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

If the user sets for example the two headers `X-Custom-User-Header` and `User-Agent` in this order, the resulting list would look like:
```
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: [ Custom user agent ]
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
X-Custom-User-Header: [ Custom user header ]
```

Thus `X-Custom-User-Header` is placed AFTER `User-Agent` even though the user requested the opposite.

This is quite tricky to solve, as it is not always clear how to combine the built-in headers and the user-supplied headers. My current thinking is to allow the user to disable the built-in headers altogether so that they can choose the order themselves.

**Comment by bratao** [comment]
@lwthiker one solution I did for this problem was to create a profile named 'chrome101_noheaders' that had no embedded headers, only the configuration of http2 and ciphers that are harder to set using libcurl wrappers. The provided headers using this followed the specified order.

**Comment by lwthiker** [comment]
Thanks @bratao , I am actually planning to make the built-in headers optional. Then the regular profiles will be usable as is, just without the headers, and the user will have to specify the exact list of headers in the desired order. The plan is that it would be possible to toggle the headers on/off through an environment variable and a parameter to the `curl_easy_impersonate()` function.

**Comment by WindBridges** [comment]
Can you please explain whether the differences in the order of the headers between `Sec-Fetch-Mode: navigate` and `Sec-Fetch-Mode: cors` are taken into account? As far as I know, at least in chome the header order is different when requesting a document (navigation) and when executing an XmlHttpRequest. 

And I also noticed that if I send request using HTTP/2 protocol, but server doesn't support it, protocol automatically downgrades to HTTP/1.1. This is correct. But chrome completely re-creates the headers into 1.1 format (uppercase, and possibly a different order), but curl-impersonate leaves them in 2.0 format (lowercase). Is this a bug?
