### ISSUE TITLE
How do you create the data that goes into the signature files?

### ISSUE THREAD

**Issue by X9DF** [lwthiker/curl-impersonate#97]
I'm interested in using and comparing the data in those files, but I do not see any file in the repo that aids with generating new entires (those which are added in the PRs). Do you have another script to read the data from a browser? If so, I'd greatly appreciate if you could share it.

I'm interested in trying to do something akin to https://tools.scrapfly.io/api/fp/ja3?extended=1 for ease of use.

**Comment by lwthiker** [comment]
Up until now I was doing it manually. Luckily the TLS signatures haven't changed much lately so it wasn't a lot of work.

If you are looking to automate it a bit more, take a look at my TS1 library: https://github.com/lwthiker/ts1
It can take a PCAP file, extract any Client Hello it finds, and generate the TLS signature.
I would at some point integrate it back into this project (mainly for the Python tests).

**Comment by lwthiker** [comment]
I'm closing this since there isn't any bug/feature request in here.
